name: 更新 Clash 规则

on:
  push:
    paths:
      - 'rule_sources.conf'
      - 'update_rules.py'
      - '.github/workflows/update-rules.yml'
      - 'rule-provider/custom/**'
  schedule:
    - cron: '0 17 * * *'  # 每天UTC时间17:00(北京时间1:00)
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest
    
    steps:
    # ========== 添加延迟 ==========
    - name: 提交后延迟
      if: github.event_name == 'push'
      run: |
        echo "代码提交后等待30秒..."
        sleep 30s
        echo "延迟结束，开始执行"
    # ========== 延迟结束 ==========
    
    - name: 检出仓库
      uses: actions/checkout@v3
      
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: 运行更新脚本
      run: python update_rules.py
      
    - name: 检查规则变化
      id: check_changes
      run: |
        if git diff --quiet -- rule-provider/; then
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "没有检测到规则变化"
        else
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "检测到规则变化，准备提交"
        fi
      
    - name: 提交并推送更改
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add -A
        git commit -m "更新规则 - $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
        git push
        
    - name: 清理工作流运行
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 5
        keep_minimum_runs: 10
