name: 更新 Clash 规则

on:
  #schedule:
    #- cron: '0 0 * * *'  # 每天 UTC 时间午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-rules:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出仓库
      uses: actions/checkout@v3
      
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: 运行更新脚本
      run: python update_rules.py
      
    - name: 提交并推送更改
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "更新规则 - $(date +'%Y-%m-%d')" && git push)
